#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipOtomasyon.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Db_StokTakip")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_Stoklar(Tbl_Stoklar instance);
    partial void UpdateTbl_Stoklar(Tbl_Stoklar instance);
    partial void DeleteTbl_Stoklar(Tbl_Stoklar instance);
    partial void InsertTbl_StokGrupları(Tbl_StokGrupları instance);
    partial void UpdateTbl_StokGrupları(Tbl_StokGrupları instance);
    partial void DeleteTbl_StokGrupları(Tbl_StokGrupları instance);
    partial void InsertTbl_CariGrupları(Tbl_CariGrupları instance);
    partial void UpdateTbl_CariGrupları(Tbl_CariGrupları instance);
    partial void DeleteTbl_CariGrupları(Tbl_CariGrupları instance);
    partial void InsertTbl_Cariler(Tbl_Cariler instance);
    partial void UpdateTbl_Cariler(Tbl_Cariler instance);
    partial void DeleteTbl_Cariler(Tbl_Cariler instance);
    partial void InsertTbl_CariHareketleri(Tbl_CariHareketleri instance);
    partial void UpdateTbl_CariHareketleri(Tbl_CariHareketleri instance);
    partial void DeleteTbl_CariHareketleri(Tbl_CariHareketleri instance);
    partial void InsertTbl_KasaHareketleri(Tbl_KasaHareketleri instance);
    partial void UpdateTbl_KasaHareketleri(Tbl_KasaHareketleri instance);
    partial void DeleteTbl_KasaHareketleri(Tbl_KasaHareketleri instance);
    partial void InsertTbl_Kasalar(Tbl_Kasalar instance);
    partial void UpdateTbl_Kasalar(Tbl_Kasalar instance);
    partial void DeleteTbl_Kasalar(Tbl_Kasalar instance);
    partial void InsertTbl_BankaHareketleri(Tbl_BankaHareketleri instance);
    partial void UpdateTbl_BankaHareketleri(Tbl_BankaHareketleri instance);
    partial void DeleteTbl_BankaHareketleri(Tbl_BankaHareketleri instance);
    partial void InsertTbl_Bankalar(Tbl_Bankalar instance);
    partial void UpdateTbl_Bankalar(Tbl_Bankalar instance);
    partial void DeleteTbl_Bankalar(Tbl_Bankalar instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::StokTakipOtomasyon.Properties.Settings.Default.Db_StokTakipConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Stoklar> Tbl_Stoklars
		{
			get
			{
				return this.GetTable<Tbl_Stoklar>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_StokGrupları> Tbl_StokGruplarıs
		{
			get
			{
				return this.GetTable<Tbl_StokGrupları>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_CariGrupları> Tbl_CariGruplarıs
		{
			get
			{
				return this.GetTable<Tbl_CariGrupları>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Cariler> Tbl_Carilers
		{
			get
			{
				return this.GetTable<Tbl_Cariler>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_CariHareketleri> Tbl_CariHareketleris
		{
			get
			{
				return this.GetTable<Tbl_CariHareketleri>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_KasaHareketleri> Tbl_KasaHareketleris
		{
			get
			{
				return this.GetTable<Tbl_KasaHareketleri>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Kasalar> Tbl_Kasalars
		{
			get
			{
				return this.GetTable<Tbl_Kasalar>();
			}
		}
		
		public System.Data.Linq.Table<VW_KasaDurum> VW_KasaDurums
		{
			get
			{
				return this.GetTable<VW_KasaDurum>();
			}
		}
		
		public System.Data.Linq.Table<VW_KasaHareketleri_Ders5_DK5> VW_KasaHareketleri_Ders5_DK5s
		{
			get
			{
				return this.GetTable<VW_KasaHareketleri_Ders5_DK5>();
			}
		}
		
		public System.Data.Linq.Table<VW_KasaListesi> VW_KasaListesis
		{
			get
			{
				return this.GetTable<VW_KasaListesi>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_BankaHareketleri> Tbl_BankaHareketleris
		{
			get
			{
				return this.GetTable<Tbl_BankaHareketleri>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Bankalar> Tbl_Bankalars
		{
			get
			{
				return this.GetTable<Tbl_Bankalar>();
			}
		}
		
		public System.Data.Linq.Table<VW_BankaDurum> VW_BankaDurums
		{
			get
			{
				return this.GetTable<VW_BankaDurum>();
			}
		}
		
		public System.Data.Linq.Table<VW_BankaHareketleri> VW_BankaHareketleris
		{
			get
			{
				return this.GetTable<VW_BankaHareketleri>();
			}
		}
		
		public System.Data.Linq.Table<VW_BankaListesi> VW_BankaListesis
		{
			get
			{
				return this.GetTable<VW_BankaListesi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Stoklar")]
	public partial class Tbl_Stoklar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _StokBarkod;
		
		private string _StokKodu;
		
		private string _StokAdı;
		
		private string _StokBirim;
		
		private System.Nullable<decimal> _StokAlisFiyat;
		
		private System.Nullable<decimal> _StokSatisFiyat;
		
		private System.Nullable<decimal> _StokAlisKDV;
		
		private System.Nullable<decimal> _StokSatisKDV;
		
		private System.Nullable<int> _StokGrupID;
		
		private System.Data.Linq.Binary _StokResim;
		
		private System.Nullable<int> _StokSaveUser;
		
		private System.Nullable<System.DateTime> _StokSaveDate;
		
		private System.Nullable<int> _StokEditUser;
		
		private System.Nullable<System.DateTime> _StokEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStokBarkodChanging(string value);
    partial void OnStokBarkodChanged();
    partial void OnStokKoduChanging(string value);
    partial void OnStokKoduChanged();
    partial void OnStokAdıChanging(string value);
    partial void OnStokAdıChanged();
    partial void OnStokBirimChanging(string value);
    partial void OnStokBirimChanged();
    partial void OnStokAlisFiyatChanging(System.Nullable<decimal> value);
    partial void OnStokAlisFiyatChanged();
    partial void OnStokSatisFiyatChanging(System.Nullable<decimal> value);
    partial void OnStokSatisFiyatChanged();
    partial void OnStokAlisKDVChanging(System.Nullable<decimal> value);
    partial void OnStokAlisKDVChanged();
    partial void OnStokSatisKDVChanging(System.Nullable<decimal> value);
    partial void OnStokSatisKDVChanged();
    partial void OnStokGrupIDChanging(System.Nullable<int> value);
    partial void OnStokGrupIDChanged();
    partial void OnStokResimChanging(System.Data.Linq.Binary value);
    partial void OnStokResimChanged();
    partial void OnStokSaveUserChanging(System.Nullable<int> value);
    partial void OnStokSaveUserChanged();
    partial void OnStokSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStokSaveDateChanged();
    partial void OnStokEditUserChanging(System.Nullable<int> value);
    partial void OnStokEditUserChanged();
    partial void OnStokEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStokEditDateChanged();
    #endregion
		
		public Tbl_Stoklar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokBarkod", DbType="NVarChar(30)")]
		public string StokBarkod
		{
			get
			{
				return this._StokBarkod;
			}
			set
			{
				if ((this._StokBarkod != value))
				{
					this.OnStokBarkodChanging(value);
					this.SendPropertyChanging();
					this._StokBarkod = value;
					this.SendPropertyChanged("StokBarkod");
					this.OnStokBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokKodu", DbType="NVarChar(20)")]
		public string StokKodu
		{
			get
			{
				return this._StokKodu;
			}
			set
			{
				if ((this._StokKodu != value))
				{
					this.OnStokKoduChanging(value);
					this.SendPropertyChanging();
					this._StokKodu = value;
					this.SendPropertyChanged("StokKodu");
					this.OnStokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAdı", DbType="NVarChar(50)")]
		public string StokAdı
		{
			get
			{
				return this._StokAdı;
			}
			set
			{
				if ((this._StokAdı != value))
				{
					this.OnStokAdıChanging(value);
					this.SendPropertyChanging();
					this._StokAdı = value;
					this.SendPropertyChanged("StokAdı");
					this.OnStokAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokBirim", DbType="NVarChar(15)")]
		public string StokBirim
		{
			get
			{
				return this._StokBirim;
			}
			set
			{
				if ((this._StokBirim != value))
				{
					this.OnStokBirimChanging(value);
					this.SendPropertyChanging();
					this._StokBirim = value;
					this.SendPropertyChanged("StokBirim");
					this.OnStokBirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAlisFiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokAlisFiyat
		{
			get
			{
				return this._StokAlisFiyat;
			}
			set
			{
				if ((this._StokAlisFiyat != value))
				{
					this.OnStokAlisFiyatChanging(value);
					this.SendPropertyChanging();
					this._StokAlisFiyat = value;
					this.SendPropertyChanged("StokAlisFiyat");
					this.OnStokAlisFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSatisFiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokSatisFiyat
		{
			get
			{
				return this._StokSatisFiyat;
			}
			set
			{
				if ((this._StokSatisFiyat != value))
				{
					this.OnStokSatisFiyatChanging(value);
					this.SendPropertyChanging();
					this._StokSatisFiyat = value;
					this.SendPropertyChanged("StokSatisFiyat");
					this.OnStokSatisFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAlisKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokAlisKDV
		{
			get
			{
				return this._StokAlisKDV;
			}
			set
			{
				if ((this._StokAlisKDV != value))
				{
					this.OnStokAlisKDVChanging(value);
					this.SendPropertyChanging();
					this._StokAlisKDV = value;
					this.SendPropertyChanged("StokAlisKDV");
					this.OnStokAlisKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSatisKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> StokSatisKDV
		{
			get
			{
				return this._StokSatisKDV;
			}
			set
			{
				if ((this._StokSatisKDV != value))
				{
					this.OnStokSatisKDVChanging(value);
					this.SendPropertyChanging();
					this._StokSatisKDV = value;
					this.SendPropertyChanged("StokSatisKDV");
					this.OnStokSatisKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokGrupID", DbType="Int")]
		public System.Nullable<int> StokGrupID
		{
			get
			{
				return this._StokGrupID;
			}
			set
			{
				if ((this._StokGrupID != value))
				{
					this.OnStokGrupIDChanging(value);
					this.SendPropertyChanging();
					this._StokGrupID = value;
					this.SendPropertyChanged("StokGrupID");
					this.OnStokGrupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokResim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StokResim
		{
			get
			{
				return this._StokResim;
			}
			set
			{
				if ((this._StokResim != value))
				{
					this.OnStokResimChanging(value);
					this.SendPropertyChanging();
					this._StokResim = value;
					this.SendPropertyChanged("StokResim");
					this.OnStokResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSaveUser", DbType="Int")]
		public System.Nullable<int> StokSaveUser
		{
			get
			{
				return this._StokSaveUser;
			}
			set
			{
				if ((this._StokSaveUser != value))
				{
					this.OnStokSaveUserChanging(value);
					this.SendPropertyChanging();
					this._StokSaveUser = value;
					this.SendPropertyChanged("StokSaveUser");
					this.OnStokSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StokSaveDate
		{
			get
			{
				return this._StokSaveDate;
			}
			set
			{
				if ((this._StokSaveDate != value))
				{
					this.OnStokSaveDateChanging(value);
					this.SendPropertyChanging();
					this._StokSaveDate = value;
					this.SendPropertyChanged("StokSaveDate");
					this.OnStokSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokEditUser", DbType="Int")]
		public System.Nullable<int> StokEditUser
		{
			get
			{
				return this._StokEditUser;
			}
			set
			{
				if ((this._StokEditUser != value))
				{
					this.OnStokEditUserChanging(value);
					this.SendPropertyChanging();
					this._StokEditUser = value;
					this.SendPropertyChanged("StokEditUser");
					this.OnStokEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StokEditDate
		{
			get
			{
				return this._StokEditDate;
			}
			set
			{
				if ((this._StokEditDate != value))
				{
					this.OnStokEditDateChanging(value);
					this.SendPropertyChanging();
					this._StokEditDate = value;
					this.SendPropertyChanged("StokEditDate");
					this.OnStokEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_StokGrupları")]
	public partial class Tbl_StokGrupları : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GrupAdı;
		
		private string _GrupKodu;
		
		private System.Nullable<int> _GrupSaveUser;
		
		private System.Nullable<System.DateTime> _GrupSaveDate;
		
		private System.Nullable<int> _GrupEditUser;
		
		private System.Nullable<System.DateTime> _GrupEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGrupAdıChanging(string value);
    partial void OnGrupAdıChanged();
    partial void OnGrupKoduChanging(string value);
    partial void OnGrupKoduChanged();
    partial void OnGrupSaveUserChanging(System.Nullable<int> value);
    partial void OnGrupSaveUserChanged();
    partial void OnGrupSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGrupSaveDateChanged();
    partial void OnGrupEditUserChanging(System.Nullable<int> value);
    partial void OnGrupEditUserChanged();
    partial void OnGrupEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGrupEditDateChanged();
    #endregion
		
		public Tbl_StokGrupları()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupAdı", DbType="NVarChar(30)")]
		public string GrupAdı
		{
			get
			{
				return this._GrupAdı;
			}
			set
			{
				if ((this._GrupAdı != value))
				{
					this.OnGrupAdıChanging(value);
					this.SendPropertyChanging();
					this._GrupAdı = value;
					this.SendPropertyChanged("GrupAdı");
					this.OnGrupAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupKodu", DbType="NVarChar(30)")]
		public string GrupKodu
		{
			get
			{
				return this._GrupKodu;
			}
			set
			{
				if ((this._GrupKodu != value))
				{
					this.OnGrupKoduChanging(value);
					this.SendPropertyChanging();
					this._GrupKodu = value;
					this.SendPropertyChanged("GrupKodu");
					this.OnGrupKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupSaveUser", DbType="Int")]
		public System.Nullable<int> GrupSaveUser
		{
			get
			{
				return this._GrupSaveUser;
			}
			set
			{
				if ((this._GrupSaveUser != value))
				{
					this.OnGrupSaveUserChanging(value);
					this.SendPropertyChanging();
					this._GrupSaveUser = value;
					this.SendPropertyChanged("GrupSaveUser");
					this.OnGrupSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GrupSaveDate
		{
			get
			{
				return this._GrupSaveDate;
			}
			set
			{
				if ((this._GrupSaveDate != value))
				{
					this.OnGrupSaveDateChanging(value);
					this.SendPropertyChanging();
					this._GrupSaveDate = value;
					this.SendPropertyChanged("GrupSaveDate");
					this.OnGrupSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupEditUser", DbType="Int")]
		public System.Nullable<int> GrupEditUser
		{
			get
			{
				return this._GrupEditUser;
			}
			set
			{
				if ((this._GrupEditUser != value))
				{
					this.OnGrupEditUserChanging(value);
					this.SendPropertyChanging();
					this._GrupEditUser = value;
					this.SendPropertyChanged("GrupEditUser");
					this.OnGrupEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GrupEditDate
		{
			get
			{
				return this._GrupEditDate;
			}
			set
			{
				if ((this._GrupEditDate != value))
				{
					this.OnGrupEditDateChanging(value);
					this.SendPropertyChanging();
					this._GrupEditDate = value;
					this.SendPropertyChanged("GrupEditDate");
					this.OnGrupEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CariGrupları")]
	public partial class Tbl_CariGrupları : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GrupAdı;
		
		private string _GrupKodu;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGrupAdıChanging(string value);
    partial void OnGrupAdıChanged();
    partial void OnGrupKoduChanging(string value);
    partial void OnGrupKoduChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_CariGrupları()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupAdı", DbType="NVarChar(30)")]
		public string GrupAdı
		{
			get
			{
				return this._GrupAdı;
			}
			set
			{
				if ((this._GrupAdı != value))
				{
					this.OnGrupAdıChanging(value);
					this.SendPropertyChanging();
					this._GrupAdı = value;
					this.SendPropertyChanged("GrupAdı");
					this.OnGrupAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupKodu", DbType="NVarChar(30)")]
		public string GrupKodu
		{
			get
			{
				return this._GrupKodu;
			}
			set
			{
				if ((this._GrupKodu != value))
				{
					this.OnGrupKoduChanging(value);
					this.SendPropertyChanging();
					this._GrupKodu = value;
					this.SendPropertyChanged("GrupKodu");
					this.OnGrupKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Cariler")]
	public partial class Tbl_Cariler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CariKodu;
		
		private string _CariAdi;
		
		private string _VergiDairesi;
		
		private string _VergiNo;
		
		private System.Nullable<int> _GrupID;
		
		private string _Ulke;
		
		private string _Sehir;
		
		private string _Ilce;
		
		private string _Adres;
		
		private string _Telefon1;
		
		private string _Telefon2;
		
		private string _Fax1;
		
		private string _Fax2;
		
		private string _WebAdresi;
		
		private string _Mail;
		
		private string _Yetkili;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCariKoduChanging(string value);
    partial void OnCariKoduChanged();
    partial void OnCariAdiChanging(string value);
    partial void OnCariAdiChanged();
    partial void OnVergiDairesiChanging(string value);
    partial void OnVergiDairesiChanged();
    partial void OnVergiNoChanging(string value);
    partial void OnVergiNoChanged();
    partial void OnGrupIDChanging(System.Nullable<int> value);
    partial void OnGrupIDChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnTelefon1Changing(string value);
    partial void OnTelefon1Changed();
    partial void OnTelefon2Changing(string value);
    partial void OnTelefon2Changed();
    partial void OnFax1Changing(string value);
    partial void OnFax1Changed();
    partial void OnFax2Changing(string value);
    partial void OnFax2Changed();
    partial void OnWebAdresiChanging(string value);
    partial void OnWebAdresiChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnYetkiliChanging(string value);
    partial void OnYetkiliChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_Cariler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKodu", DbType="NVarChar(30)")]
		public string CariKodu
		{
			get
			{
				return this._CariKodu;
			}
			set
			{
				if ((this._CariKodu != value))
				{
					this.OnCariKoduChanging(value);
					this.SendPropertyChanging();
					this._CariKodu = value;
					this.SendPropertyChanged("CariKodu");
					this.OnCariKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariAdi", DbType="NVarChar(30)")]
		public string CariAdi
		{
			get
			{
				return this._CariAdi;
			}
			set
			{
				if ((this._CariAdi != value))
				{
					this.OnCariAdiChanging(value);
					this.SendPropertyChanging();
					this._CariAdi = value;
					this.SendPropertyChanged("CariAdi");
					this.OnCariAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiDairesi", DbType="NVarChar(50)")]
		public string VergiDairesi
		{
			get
			{
				return this._VergiDairesi;
			}
			set
			{
				if ((this._VergiDairesi != value))
				{
					this.OnVergiDairesiChanging(value);
					this.SendPropertyChanging();
					this._VergiDairesi = value;
					this.SendPropertyChanged("VergiDairesi");
					this.OnVergiDairesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiNo", DbType="NVarChar(20)")]
		public string VergiNo
		{
			get
			{
				return this._VergiNo;
			}
			set
			{
				if ((this._VergiNo != value))
				{
					this.OnVergiNoChanging(value);
					this.SendPropertyChanging();
					this._VergiNo = value;
					this.SendPropertyChanged("VergiNo");
					this.OnVergiNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupID", DbType="Int")]
		public System.Nullable<int> GrupID
		{
			get
			{
				return this._GrupID;
			}
			set
			{
				if ((this._GrupID != value))
				{
					this.OnGrupIDChanging(value);
					this.SendPropertyChanging();
					this._GrupID = value;
					this.SendPropertyChanged("GrupID");
					this.OnGrupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(30)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(30)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(30)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon1", DbType="NVarChar(11)")]
		public string Telefon1
		{
			get
			{
				return this._Telefon1;
			}
			set
			{
				if ((this._Telefon1 != value))
				{
					this.OnTelefon1Changing(value);
					this.SendPropertyChanging();
					this._Telefon1 = value;
					this.SendPropertyChanged("Telefon1");
					this.OnTelefon1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon2", DbType="NVarChar(11)")]
		public string Telefon2
		{
			get
			{
				return this._Telefon2;
			}
			set
			{
				if ((this._Telefon2 != value))
				{
					this.OnTelefon2Changing(value);
					this.SendPropertyChanging();
					this._Telefon2 = value;
					this.SendPropertyChanged("Telefon2");
					this.OnTelefon2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax1", DbType="NVarChar(11)")]
		public string Fax1
		{
			get
			{
				return this._Fax1;
			}
			set
			{
				if ((this._Fax1 != value))
				{
					this.OnFax1Changing(value);
					this.SendPropertyChanging();
					this._Fax1 = value;
					this.SendPropertyChanged("Fax1");
					this.OnFax1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax2", DbType="NVarChar(11)")]
		public string Fax2
		{
			get
			{
				return this._Fax2;
			}
			set
			{
				if ((this._Fax2 != value))
				{
					this.OnFax2Changing(value);
					this.SendPropertyChanging();
					this._Fax2 = value;
					this.SendPropertyChanged("Fax2");
					this.OnFax2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAdresi", DbType="NVarChar(150)")]
		public string WebAdresi
		{
			get
			{
				return this._WebAdresi;
			}
			set
			{
				if ((this._WebAdresi != value))
				{
					this.OnWebAdresiChanging(value);
					this.SendPropertyChanging();
					this._WebAdresi = value;
					this.SendPropertyChanged("WebAdresi");
					this.OnWebAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(250)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili", DbType="NVarChar(50)")]
		public string Yetkili
		{
			get
			{
				return this._Yetkili;
			}
			set
			{
				if ((this._Yetkili != value))
				{
					this.OnYetkiliChanging(value);
					this.SendPropertyChanging();
					this._Yetkili = value;
					this.SendPropertyChanged("Yetkili");
					this.OnYetkiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CariHareketleri")]
	public partial class Tbl_CariHareketleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _CariID;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakID;
		
		private System.Nullable<decimal> _Borc;
		
		private System.Nullable<decimal> _Alacak;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _Tipi;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCariIDChanging(System.Nullable<int> value);
    partial void OnCariIDChanged();
    partial void OnEvrakTuruChanging(string value);
    partial void OnEvrakTuruChanged();
    partial void OnEvrakIDChanging(System.Nullable<int> value);
    partial void OnEvrakIDChanged();
    partial void OnBorcChanging(System.Nullable<decimal> value);
    partial void OnBorcChanged();
    partial void OnAlacakChanging(System.Nullable<decimal> value);
    partial void OnAlacakChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnTipiChanging(string value);
    partial void OnTipiChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_CariHareketleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariID", DbType="Int")]
		public System.Nullable<int> CariID
		{
			get
			{
				return this._CariID;
			}
			set
			{
				if ((this._CariID != value))
				{
					this.OnCariIDChanging(value);
					this.SendPropertyChanging();
					this._CariID = value;
					this.SendPropertyChanged("CariID");
					this.OnCariIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(30)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this.OnEvrakTuruChanging(value);
					this.SendPropertyChanging();
					this._EvrakTuru = value;
					this.SendPropertyChanged("EvrakTuru");
					this.OnEvrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakID", DbType="Int")]
		public System.Nullable<int> EvrakID
		{
			get
			{
				return this._EvrakID;
			}
			set
			{
				if ((this._EvrakID != value))
				{
					this.OnEvrakIDChanging(value);
					this.SendPropertyChanging();
					this._EvrakID = value;
					this.SendPropertyChanged("EvrakID");
					this.OnEvrakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borc", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Borc
		{
			get
			{
				return this._Borc;
			}
			set
			{
				if ((this._Borc != value))
				{
					this.OnBorcChanging(value);
					this.SendPropertyChanging();
					this._Borc = value;
					this.SendPropertyChanged("Borc");
					this.OnBorcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alacak", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Alacak
		{
			get
			{
				return this._Alacak;
			}
			set
			{
				if ((this._Alacak != value))
				{
					this.OnAlacakChanging(value);
					this.SendPropertyChanging();
					this._Alacak = value;
					this.SendPropertyChanged("Alacak");
					this.OnAlacakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipi", DbType="NVarChar(25)")]
		public string Tipi
		{
			get
			{
				return this._Tipi;
			}
			set
			{
				if ((this._Tipi != value))
				{
					this.OnTipiChanging(value);
					this.SendPropertyChanging();
					this._Tipi = value;
					this.SendPropertyChanged("Tipi");
					this.OnTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_KasaHareketleri")]
	public partial class Tbl_KasaHareketleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _KasaID;
		
		private System.Nullable<int> _CarID;
		
		private string _BelgeNo;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakID;
		
		private System.Nullable<System.DateTime> _Tairh;
		
		private string _GCKodu;
		
		private System.Nullable<decimal> _Tutar;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKasaIDChanging(System.Nullable<int> value);
    partial void OnKasaIDChanged();
    partial void OnCarIDChanging(System.Nullable<int> value);
    partial void OnCarIDChanged();
    partial void OnBelgeNoChanging(string value);
    partial void OnBelgeNoChanged();
    partial void OnEvrakTuruChanging(string value);
    partial void OnEvrakTuruChanged();
    partial void OnEvrakIDChanging(System.Nullable<int> value);
    partial void OnEvrakIDChanged();
    partial void OnTairhChanging(System.Nullable<System.DateTime> value);
    partial void OnTairhChanged();
    partial void OnGCKoduChanging(string value);
    partial void OnGCKoduChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_KasaHareketleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaID", DbType="Int")]
		public System.Nullable<int> KasaID
		{
			get
			{
				return this._KasaID;
			}
			set
			{
				if ((this._KasaID != value))
				{
					this.OnKasaIDChanging(value);
					this.SendPropertyChanging();
					this._KasaID = value;
					this.SendPropertyChanged("KasaID");
					this.OnKasaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", DbType="Int")]
		public System.Nullable<int> CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					this.OnCarIDChanging(value);
					this.SendPropertyChanging();
					this._CarID = value;
					this.SendPropertyChanged("CarID");
					this.OnCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BelgeNo", DbType="NVarChar(30)")]
		public string BelgeNo
		{
			get
			{
				return this._BelgeNo;
			}
			set
			{
				if ((this._BelgeNo != value))
				{
					this.OnBelgeNoChanging(value);
					this.SendPropertyChanging();
					this._BelgeNo = value;
					this.SendPropertyChanged("BelgeNo");
					this.OnBelgeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(30)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this.OnEvrakTuruChanging(value);
					this.SendPropertyChanging();
					this._EvrakTuru = value;
					this.SendPropertyChanged("EvrakTuru");
					this.OnEvrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakID", DbType="Int")]
		public System.Nullable<int> EvrakID
		{
			get
			{
				return this._EvrakID;
			}
			set
			{
				if ((this._EvrakID != value))
				{
					this.OnEvrakIDChanging(value);
					this.SendPropertyChanging();
					this._EvrakID = value;
					this.SendPropertyChanged("EvrakID");
					this.OnEvrakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tairh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tairh
		{
			get
			{
				return this._Tairh;
			}
			set
			{
				if ((this._Tairh != value))
				{
					this.OnTairhChanging(value);
					this.SendPropertyChanging();
					this._Tairh = value;
					this.SendPropertyChanged("Tairh");
					this.OnTairhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKodu", DbType="NVarChar(1)")]
		public string GCKodu
		{
			get
			{
				return this._GCKodu;
			}
			set
			{
				if ((this._GCKodu != value))
				{
					this.OnGCKoduChanging(value);
					this.SendPropertyChanging();
					this._GCKodu = value;
					this.SendPropertyChanged("GCKodu");
					this.OnGCKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Kasalar")]
	public partial class Tbl_Kasalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KasaKodu;
		
		private string _KasaAdi;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKasaKoduChanging(string value);
    partial void OnKasaKoduChanged();
    partial void OnKasaAdiChanging(string value);
    partial void OnKasaAdiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_Kasalar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaKodu", DbType="NVarChar(30)")]
		public string KasaKodu
		{
			get
			{
				return this._KasaKodu;
			}
			set
			{
				if ((this._KasaKodu != value))
				{
					this.OnKasaKoduChanging(value);
					this.SendPropertyChanging();
					this._KasaKodu = value;
					this.SendPropertyChanged("KasaKodu");
					this.OnKasaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaAdi", DbType="NVarChar(30)")]
		public string KasaAdi
		{
			get
			{
				return this._KasaAdi;
			}
			set
			{
				if ((this._KasaAdi != value))
				{
					this.OnKasaAdiChanging(value);
					this.SendPropertyChanging();
					this._KasaAdi = value;
					this.SendPropertyChanged("KasaAdi");
					this.OnKasaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KasaDurum")]
	public partial class VW_KasaDurum
	{
		
		private System.Nullable<int> _KasaID;
		
		private System.Nullable<decimal> _Gırıs;
		
		private System.Nullable<decimal> _Cikis;
		
		private System.Nullable<decimal> _Bakiye;
		
		public VW_KasaDurum()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaID", DbType="Int")]
		public System.Nullable<int> KasaID
		{
			get
			{
				return this._KasaID;
			}
			set
			{
				if ((this._KasaID != value))
				{
					this._KasaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gırıs", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Gırıs
		{
			get
			{
				return this._Gırıs;
			}
			set
			{
				if ((this._Gırıs != value))
				{
					this._Gırıs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikis", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Cikis
		{
			get
			{
				return this._Cikis;
			}
			set
			{
				if ((this._Cikis != value))
				{
					this._Cikis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bakiye", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Bakiye
		{
			get
			{
				return this._Bakiye;
			}
			set
			{
				if ((this._Bakiye != value))
				{
					this._Bakiye = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KasaHareketleri_Ders5_DK5")]
	public partial class VW_KasaHareketleri_Ders5_DK5
	{
		
		private int _Id;
		
		private System.Nullable<int> _KasaID;
		
		private System.Nullable<int> _CarID;
		
		private string _KasaKodu;
		
		private string _KasaAdi;
		
		private string _CariKodu;
		
		private string _CariAdi;
		
		private string _BelgeNo;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakID;
		
		private System.Nullable<System.DateTime> _Tairh;
		
		private System.Nullable<decimal> _Gırıs;
		
		private System.Nullable<decimal> _Cikis;
		
		private string _Aciklama;
		
		public VW_KasaHareketleri_Ders5_DK5()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaID", DbType="Int")]
		public System.Nullable<int> KasaID
		{
			get
			{
				return this._KasaID;
			}
			set
			{
				if ((this._KasaID != value))
				{
					this._KasaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", DbType="Int")]
		public System.Nullable<int> CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					this._CarID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaKodu", DbType="NVarChar(30)")]
		public string KasaKodu
		{
			get
			{
				return this._KasaKodu;
			}
			set
			{
				if ((this._KasaKodu != value))
				{
					this._KasaKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaAdi", DbType="NVarChar(30)")]
		public string KasaAdi
		{
			get
			{
				return this._KasaAdi;
			}
			set
			{
				if ((this._KasaAdi != value))
				{
					this._KasaAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKodu", DbType="NVarChar(30)")]
		public string CariKodu
		{
			get
			{
				return this._CariKodu;
			}
			set
			{
				if ((this._CariKodu != value))
				{
					this._CariKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariAdi", DbType="NVarChar(30)")]
		public string CariAdi
		{
			get
			{
				return this._CariAdi;
			}
			set
			{
				if ((this._CariAdi != value))
				{
					this._CariAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BelgeNo", DbType="NVarChar(30)")]
		public string BelgeNo
		{
			get
			{
				return this._BelgeNo;
			}
			set
			{
				if ((this._BelgeNo != value))
				{
					this._BelgeNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(30)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this._EvrakTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakID", DbType="Int")]
		public System.Nullable<int> EvrakID
		{
			get
			{
				return this._EvrakID;
			}
			set
			{
				if ((this._EvrakID != value))
				{
					this._EvrakID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tairh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tairh
		{
			get
			{
				return this._Tairh;
			}
			set
			{
				if ((this._Tairh != value))
				{
					this._Tairh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gırıs", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Gırıs
		{
			get
			{
				return this._Gırıs;
			}
			set
			{
				if ((this._Gırıs != value))
				{
					this._Gırıs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikis", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Cikis
		{
			get
			{
				return this._Cikis;
			}
			set
			{
				if ((this._Cikis != value))
				{
					this._Cikis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this._Aciklama = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KasaListesi")]
	public partial class VW_KasaListesi
	{
		
		private int _Id;
		
		private string _KasaKodu;
		
		private string _KasaAdi;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _Gırıs;
		
		private System.Nullable<decimal> _Cikis;
		
		private System.Nullable<decimal> _Bakiye;
		
		public VW_KasaListesi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaKodu", DbType="NVarChar(30)")]
		public string KasaKodu
		{
			get
			{
				return this._KasaKodu;
			}
			set
			{
				if ((this._KasaKodu != value))
				{
					this._KasaKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KasaAdi", DbType="NVarChar(30)")]
		public string KasaAdi
		{
			get
			{
				return this._KasaAdi;
			}
			set
			{
				if ((this._KasaAdi != value))
				{
					this._KasaAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this._Aciklama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gırıs", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Gırıs
		{
			get
			{
				return this._Gırıs;
			}
			set
			{
				if ((this._Gırıs != value))
				{
					this._Gırıs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikis", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Cikis
		{
			get
			{
				return this._Cikis;
			}
			set
			{
				if ((this._Cikis != value))
				{
					this._Cikis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bakiye", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Bakiye
		{
			get
			{
				return this._Bakiye;
			}
			set
			{
				if ((this._Bakiye != value))
				{
					this._Bakiye = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_BankaHareketleri")]
	public partial class Tbl_BankaHareketleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BankaID;
		
		private System.Nullable<int> _CariID;
		
		private string _BelgeNo;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakID;
		
		private string _GCKodu;
		
		private System.Nullable<decimal> _Tutar;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBankaIDChanging(System.Nullable<int> value);
    partial void OnBankaIDChanged();
    partial void OnCariIDChanging(System.Nullable<int> value);
    partial void OnCariIDChanged();
    partial void OnBelgeNoChanging(string value);
    partial void OnBelgeNoChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnEvrakTuruChanging(string value);
    partial void OnEvrakTuruChanged();
    partial void OnEvrakIDChanging(System.Nullable<int> value);
    partial void OnEvrakIDChanged();
    partial void OnGCKoduChanging(string value);
    partial void OnGCKoduChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_BankaHareketleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankaID", DbType="Int")]
		public System.Nullable<int> BankaID
		{
			get
			{
				return this._BankaID;
			}
			set
			{
				if ((this._BankaID != value))
				{
					this.OnBankaIDChanging(value);
					this.SendPropertyChanging();
					this._BankaID = value;
					this.SendPropertyChanged("BankaID");
					this.OnBankaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariID", DbType="Int")]
		public System.Nullable<int> CariID
		{
			get
			{
				return this._CariID;
			}
			set
			{
				if ((this._CariID != value))
				{
					this.OnCariIDChanging(value);
					this.SendPropertyChanging();
					this._CariID = value;
					this.SendPropertyChanged("CariID");
					this.OnCariIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BelgeNo", DbType="NVarChar(30)")]
		public string BelgeNo
		{
			get
			{
				return this._BelgeNo;
			}
			set
			{
				if ((this._BelgeNo != value))
				{
					this.OnBelgeNoChanging(value);
					this.SendPropertyChanging();
					this._BelgeNo = value;
					this.SendPropertyChanged("BelgeNo");
					this.OnBelgeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(30)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this.OnEvrakTuruChanging(value);
					this.SendPropertyChanging();
					this._EvrakTuru = value;
					this.SendPropertyChanged("EvrakTuru");
					this.OnEvrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakID", DbType="Int")]
		public System.Nullable<int> EvrakID
		{
			get
			{
				return this._EvrakID;
			}
			set
			{
				if ((this._EvrakID != value))
				{
					this.OnEvrakIDChanging(value);
					this.SendPropertyChanging();
					this._EvrakID = value;
					this.SendPropertyChanged("EvrakID");
					this.OnEvrakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKodu", DbType="NVarChar(1)")]
		public string GCKodu
		{
			get
			{
				return this._GCKodu;
			}
			set
			{
				if ((this._GCKodu != value))
				{
					this.OnGCKoduChanging(value);
					this.SendPropertyChanging();
					this._GCKodu = value;
					this.SendPropertyChanged("GCKodu");
					this.OnGCKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Bankalar")]
	public partial class Tbl_Bankalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _HesapNo;
		
		private string _IBAN;
		
		private string _BankaAdi;
		
		private string _HesapAdi;
		
		private string _Sube;
		
		private string _Tel;
		
		private string _Adres;
		
		private string _Temsilci;
		
		private string _TemsilciEmail;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHesapNoChanging(string value);
    partial void OnHesapNoChanged();
    partial void OnIBANChanging(string value);
    partial void OnIBANChanged();
    partial void OnBankaAdiChanging(string value);
    partial void OnBankaAdiChanged();
    partial void OnHesapAdiChanging(string value);
    partial void OnHesapAdiChanged();
    partial void OnSubeChanging(string value);
    partial void OnSubeChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnTemsilciChanging(string value);
    partial void OnTemsilciChanged();
    partial void OnTemsilciEmailChanging(string value);
    partial void OnTemsilciEmailChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public Tbl_Bankalar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapNo", DbType="NVarChar(30)")]
		public string HesapNo
		{
			get
			{
				return this._HesapNo;
			}
			set
			{
				if ((this._HesapNo != value))
				{
					this.OnHesapNoChanging(value);
					this.SendPropertyChanging();
					this._HesapNo = value;
					this.SendPropertyChanged("HesapNo");
					this.OnHesapNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this.OnIBANChanging(value);
					this.SendPropertyChanging();
					this._IBAN = value;
					this.SendPropertyChanged("IBAN");
					this.OnIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankaAdi", DbType="NVarChar(30)")]
		public string BankaAdi
		{
			get
			{
				return this._BankaAdi;
			}
			set
			{
				if ((this._BankaAdi != value))
				{
					this.OnBankaAdiChanging(value);
					this.SendPropertyChanging();
					this._BankaAdi = value;
					this.SendPropertyChanged("BankaAdi");
					this.OnBankaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapAdi", DbType="NVarChar(30)")]
		public string HesapAdi
		{
			get
			{
				return this._HesapAdi;
			}
			set
			{
				if ((this._HesapAdi != value))
				{
					this.OnHesapAdiChanging(value);
					this.SendPropertyChanging();
					this._HesapAdi = value;
					this.SendPropertyChanged("HesapAdi");
					this.OnHesapAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sube", DbType="NVarChar(30)")]
		public string Sube
		{
			get
			{
				return this._Sube;
			}
			set
			{
				if ((this._Sube != value))
				{
					this.OnSubeChanging(value);
					this.SendPropertyChanging();
					this._Sube = value;
					this.SendPropertyChanged("Sube");
					this.OnSubeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(16)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temsilci", DbType="NVarChar(50)")]
		public string Temsilci
		{
			get
			{
				return this._Temsilci;
			}
			set
			{
				if ((this._Temsilci != value))
				{
					this.OnTemsilciChanging(value);
					this.SendPropertyChanging();
					this._Temsilci = value;
					this.SendPropertyChanged("Temsilci");
					this.OnTemsilciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemsilciEmail", DbType="NVarChar(150)")]
		public string TemsilciEmail
		{
			get
			{
				return this._TemsilciEmail;
			}
			set
			{
				if ((this._TemsilciEmail != value))
				{
					this.OnTemsilciEmailChanging(value);
					this.SendPropertyChanging();
					this._TemsilciEmail = value;
					this.SendPropertyChanged("TemsilciEmail");
					this.OnTemsilciEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BankaDurum")]
	public partial class VW_BankaDurum
	{
		
		private int _Id;
		
		private System.Nullable<decimal> _Gırıs;
		
		private System.Nullable<decimal> _Cikis;
		
		private System.Nullable<decimal> _Bakiye;
		
		public VW_BankaDurum()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gırıs", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Gırıs
		{
			get
			{
				return this._Gırıs;
			}
			set
			{
				if ((this._Gırıs != value))
				{
					this._Gırıs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikis", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Cikis
		{
			get
			{
				return this._Cikis;
			}
			set
			{
				if ((this._Cikis != value))
				{
					this._Cikis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bakiye", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Bakiye
		{
			get
			{
				return this._Bakiye;
			}
			set
			{
				if ((this._Bakiye != value))
				{
					this._Bakiye = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BankaHareketleri")]
	public partial class VW_BankaHareketleri
	{
		
		private int _Id;
		
		private System.Nullable<int> _BankaID;
		
		private System.Nullable<int> _CariID;
		
		private string _BelgeNo;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _EvrakTuru;
		
		private System.Nullable<int> _EvrakID;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _Gırıs;
		
		private System.Nullable<decimal> _Cikis;
		
		private string _HesapAdi;
		
		private string _HesapNo;
		
		public VW_BankaHareketleri()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankaID", DbType="Int")]
		public System.Nullable<int> BankaID
		{
			get
			{
				return this._BankaID;
			}
			set
			{
				if ((this._BankaID != value))
				{
					this._BankaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariID", DbType="Int")]
		public System.Nullable<int> CariID
		{
			get
			{
				return this._CariID;
			}
			set
			{
				if ((this._CariID != value))
				{
					this._CariID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BelgeNo", DbType="NVarChar(30)")]
		public string BelgeNo
		{
			get
			{
				return this._BelgeNo;
			}
			set
			{
				if ((this._BelgeNo != value))
				{
					this._BelgeNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTuru", DbType="NVarChar(30)")]
		public string EvrakTuru
		{
			get
			{
				return this._EvrakTuru;
			}
			set
			{
				if ((this._EvrakTuru != value))
				{
					this._EvrakTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakID", DbType="Int")]
		public System.Nullable<int> EvrakID
		{
			get
			{
				return this._EvrakID;
			}
			set
			{
				if ((this._EvrakID != value))
				{
					this._EvrakID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this._Aciklama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gırıs", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Gırıs
		{
			get
			{
				return this._Gırıs;
			}
			set
			{
				if ((this._Gırıs != value))
				{
					this._Gırıs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikis", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Cikis
		{
			get
			{
				return this._Cikis;
			}
			set
			{
				if ((this._Cikis != value))
				{
					this._Cikis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapAdi", DbType="NVarChar(30)")]
		public string HesapAdi
		{
			get
			{
				return this._HesapAdi;
			}
			set
			{
				if ((this._HesapAdi != value))
				{
					this._HesapAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapNo", DbType="NVarChar(30)")]
		public string HesapNo
		{
			get
			{
				return this._HesapNo;
			}
			set
			{
				if ((this._HesapNo != value))
				{
					this._HesapNo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BankaListesi")]
	public partial class VW_BankaListesi
	{
		
		private int _Id;
		
		private string _HesapNo;
		
		private string _IBAN;
		
		private string _BankaAdi;
		
		private string _HesapAdi;
		
		private System.Nullable<decimal> _Gırıs;
		
		private System.Nullable<decimal> _Cikis;
		
		private System.Nullable<decimal> _Bakiye;
		
		public VW_BankaListesi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapNo", DbType="NVarChar(30)")]
		public string HesapNo
		{
			get
			{
				return this._HesapNo;
			}
			set
			{
				if ((this._HesapNo != value))
				{
					this._HesapNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this._IBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankaAdi", DbType="NVarChar(30)")]
		public string BankaAdi
		{
			get
			{
				return this._BankaAdi;
			}
			set
			{
				if ((this._BankaAdi != value))
				{
					this._BankaAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapAdi", DbType="NVarChar(30)")]
		public string HesapAdi
		{
			get
			{
				return this._HesapAdi;
			}
			set
			{
				if ((this._HesapAdi != value))
				{
					this._HesapAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gırıs", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Gırıs
		{
			get
			{
				return this._Gırıs;
			}
			set
			{
				if ((this._Gırıs != value))
				{
					this._Gırıs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikis", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Cikis
		{
			get
			{
				return this._Cikis;
			}
			set
			{
				if ((this._Cikis != value))
				{
					this._Cikis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bakiye", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Bakiye
		{
			get
			{
				return this._Bakiye;
			}
			set
			{
				if ((this._Bakiye != value))
				{
					this._Bakiye = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
